// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yliozpgdxzrsbntcuckr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsaW96cGdkeHpyc2JudGN1Y2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjIxMzQsImV4cCI6MjA2NTMzODEzNH0.P2aWhVoOKqsVS9MenJiJoE58J87jZGd0ThlwLvEC19A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);